'use strict';

/**
 * Krishi Mitra — Phone Authentication & Supabase Persistence Router
 *
 * Verifies Firebase ID Tokens generated by frontend Phone Auth via the
 * Firebase Admin SDK. Cryptographically guarantees the phone number was
 * verified by SMS, then upserts the record into Supabase.
 */

const express = require('express');
const router = express.Router();
const supabase = require('./supabase');

let admin = null;
let firebaseAdminInitialized = false;
let initError = null;

function getFirebaseAdmin() {
  if (firebaseAdminInitialized) return admin;

  try {
    admin = require('firebase-admin');
  } catch (e) {
    initError = 'firebase-admin package is not installed';
    console.warn('[phone-auth]', initError);
    return null;
  }

  if (admin.apps && admin.apps.length > 0) {
    firebaseAdminInitialized = true;
    return admin;
  }

  const rawJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  const filePath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH;

  let credentials = null;

  if (rawJson && rawJson.trim()) {
    try {
      // Support both raw JSON and base64-encoded JSON for deployment convenience
      const trimmed = rawJson.trim();
      const jsonStr = trimmed.startsWith('{')
        ? trimmed
        : Buffer.from(trimmed, 'base64').toString('utf8');
      credentials = JSON.parse(jsonStr);
    } catch (err) {
      initError = `Failed to parse FIREBASE_SERVICE_ACCOUNT_JSON: ${err.message}`;
      console.error('[phone-auth]', initError);
      return null;
    }
  } else if (filePath && filePath.trim()) {
    try {
      const fs = require('fs');
      const content = fs.readFileSync(filePath.trim(), 'utf8');
      credentials = JSON.parse(content);
    } catch (err) {
      initError = `Failed to read service account from FIREBASE_SERVICE_ACCOUNT_PATH: ${err.message}`;
      console.error('[phone-auth]', initError);
      return null;
    }
  }

  if (credentials) {
    try {
      admin.initializeApp({
        credential: admin.credential.cert(credentials)
      });
      firebaseAdminInitialized = true;
      initError = null;
      console.log('[phone-auth] Firebase Admin SDK initialized successfully.');
      return admin;
    } catch (err) {
      initError = `Firebase Admin initializeApp failed: ${err.message}`;
      console.error('[phone-auth]', initError);
      return null;
    }
  }

  initError = 'FIREBASE_SERVICE_ACCOUNT_JSON is not configured in environment';
  return null;
}

// Attempt initialization on startup
getFirebaseAdmin();

/**
 * POST /api/phone/confirm
 * Body: { idToken: string, phoneNumber: string }
 *
 * 1. Validates input
 * 2. Cryptographically verifies idToken with Firebase Admin SDK
 * 3. Asserts decodedToken.phone_number matches the claimed phoneNumber
 * 4. Persists verified phone to Supabase table ('profiles' or SUPABASE_PHONE_TABLE)
 */
router.post('/confirm', async (req, res) => {
  const { idToken, phoneNumber } = req.body || {};

  if (!idToken || typeof idToken !== 'string' || !idToken.trim()) {
    return res.status(400).json({ error: 'Missing or invalid idToken parameter' });
  }

  if (!phoneNumber || typeof phoneNumber !== 'string' || !phoneNumber.trim()) {
    return res.status(400).json({ error: 'Missing or invalid phoneNumber parameter' });
  }

  const cleanPhone = phoneNumber.trim();
  const fbAdmin = getFirebaseAdmin();

  if (!fbAdmin || !firebaseAdminInitialized) {
    return res.status(503).json({
      error: 'Firebase Admin SDK is not configured on this server',
      details: initError || 'FIREBASE_SERVICE_ACCOUNT_JSON missing'
    });
  }

  try {
    // 1. Cryptographically decode and verify Firebase ID Token
    const decodedToken = await fbAdmin.auth().verifyIdToken(idToken.trim());

    // 2. Security validation: Token must have verified phone number
    const verifiedPhone = decodedToken.phone_number;
    if (!verifiedPhone) {
      return res.status(403).json({
        error: 'Forbidden: Provided Firebase token does not contain a verified phone number'
      });
    }

    // 3. Prevent spoofing: Claimed phone number MUST match token phone number
    if (verifiedPhone !== cleanPhone) {
      return res.status(403).json({
        error: 'Forbidden: Claimed phone number does not match verified token phone number',
        tokenPhone: verifiedPhone,
        requestedPhone: cleanPhone
      });
    }

    // 4. Upsert verified phone record into Supabase
    const tableName = process.env.SUPABASE_PHONE_TABLE || 'profiles';
    const supabaseClient = supabase.getClient();
    let persistedToSupabase = false;
    let dbDetails = null;

    if (supabaseClient) {
      try {
        const { data, error } = await supabaseClient
          .from(tableName)
          .upsert({
            phone: cleanPhone,
            phone_verified: true,
            firebase_uid: decodedToken.uid,
            verified_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }, { onConflict: 'phone' })
          .select();

        if (error) {
          console.error(`[phone-auth] Supabase write failed on table '${tableName}':`, error.message);
          return res.status(500).json({
            error: 'Failed to save verified phone to Supabase database',
            details: error.message,
            table: tableName
          });
        }

        persistedToSupabase = true;
        dbDetails = data;
        console.log(`[phone-auth] Verified phone ${cleanPhone} saved to Supabase '${tableName}' (UID: ${decodedToken.uid})`);
      } catch (dbErr) {
        console.error(`[phone-auth] Database exception on table '${tableName}':`, dbErr.message);
        return res.status(500).json({
          error: 'Database communication error',
          details: dbErr.message
        });
      }
    } else {
      console.warn('[phone-auth] Supabase is not configured (SUPABASE_URL missing). Token verified but DB persistence skipped.');
    }

    return res.json({
      success: true,
      message: 'Phone number verified successfully',
      phoneNumber: cleanPhone,
      uid: decodedToken.uid,
      persisted_to_supabase: persistedToSupabase,
      data: dbDetails
    });
  } catch (verifyErr) {
    console.error('[phone-auth] Token verification rejected:', verifyErr.message);
    return res.status(401).json({
      error: 'Invalid, forged, or expired Firebase ID token',
      details: verifyErr.message
    });
  }
});

/**
 * GET /api/phone/status
 * Diagnostic endpoint for verifying service status without exposing secrets
 */
router.get('/status', (req, res) => {
  const fbAdmin = getFirebaseAdmin();
  res.json({
    firebase_admin_configured: Boolean(fbAdmin && firebaseAdminInitialized),
    supabase_configured: supabase.isConfigured(),
    target_table: process.env.SUPABASE_PHONE_TABLE || 'profiles'
  });
});

module.exports = router;
